const PLAYERS: string[] = [
  'Andrade Nicolas (P) (PIS)',
  'Audero Emil (P) (CRE)',
  'Butez Jean (P) (COM)',
  'Caprile Elia (P) (CAG)',
  'Carnesecchi Marco (P) (ATA)',
  'Cavlina Nikola (P) (COM)',
  'Ciocci Giuseppe (P) (CAG)',
  'Contini Nikita (P) (NAP)',
  'Corvi Edoardo (P) (PAR)',
  'De Gea David (P) (FIO)',
  'Di Gennaro Raffaele (P) (INT)',
  'Di Gregorio Michele (P) (JUV)',
  'Falcone Wladimiro (P) (LEC)',
  'Fruchtl Christian (P) (LEC)',
  'Furlanetto Alessio (P) (LAZ)',
  'Gollini Pierluigi (P) (ROM)',
  'Israel Wibmer Franco (P) (TOR)',
  'Leali Nicola (P) (GEN)',
  'Lezzerini Luca (P) (FIO)',
  'Maignan Mike (P) (MIL)',
  'Mandas Christos (P) (LAZ)',
  'Martinelli Tommaso (P) (FIO)',
  'Martinez Josep (P) (INT)',
  'Meret Alex (P) (NAP)',
  'Milinkovic Savic Vanja (P) (NAP)',
  'Montipà Lorenzo (P) (VER)',
  'Muric Arijanet (P) (SAS)',
  'Nava Lapo (P) (CRE)',
  'Nunziante Alessandro (P) (UDI)',
  'Okoye Maduka (P) (UDI)',
  'Padelli Daniele (P) (UDI)',
  'Paleari Alberto (P) (TOR)',
  'Perilli Simone (P) (VER)',
  'Perin Mattia (P) (JUV)',
  'Pessina Massimo (P) (BOL)',
  'Pinsoglio Carlo (P) (JUV)',
  'Popa Mihai (P) (TOR)',
  'Provedel Ivan (P) (LAZ)',
  'Radunovic Boris (P) (CAG)',
  'Ravaglia Federico (P) (BOL)',
  'Rinaldi Filippo (P) (PAR)',
  'Rossi Francesco (P) (ATA)',
  'Samooja Jasper (P) (LEC)',
  'Satalino Giacomo (P) (SAS)',
  'Sava Razvan (P) (UDI)',
  'Scuffet Simone (P) (PIS)',
  'Semper Adrian (P) (PIS)',
  'Siegrist Benjamin (P) (GEN)',
  'Silvestri Marco (P) (CRE)',
  'Skorupski Lukasz (P) (BOL)',
  'Sommariva Daniele (P) (GEN)',
  'Sommer Yann (P) (INT)',
  'Sportiello Marco (P) (ATA)',
  'Suzuki Zion (P) (PAR)',
  'Svilar Mile (P) (ROM)',
  'Terracciano Pietro (P) (MIL)',
  'Toniolo Giacomo (P) (VER)',
  'Torriani Lorenzo (P) (MIL)',
  'Turati Stefano (P) (SAS)',
  'Vasquez Devis (P) (ROM)',
  'Vigorito Mauro (P) (COM)',
  'Zacchi Gioele (P) (SAS)',

  //difensori
  'Acerbi Francesco (D) (INT)',
  'Ahanor Honest (D) (ATA)',
  'Akanji Manuel Obafemi (D) (INT)',
  'Albiol Raoul (D) (PIS)',
  'Angelino Jose Angel (D) (ROM)',
  'Angori Samuele (D) (PIS)',
  'Athekame Zachary (D) (MIL)',
  'Augusto Carlos (D) (INT)',
  'Bakker Mitchel (D) (ATA)',
  'Barbieri Tommaso (D) (CRE)',
  'Bartesaghi Davide (D) (MIL)',
  'Baschirotto Federico (D) (CRE)',
  'Bastoni Alessandro (D) (INT)',
  'Belghali Rafik (D) (VER)',
  'Bella-Kotchap Armel (D) (VER)',
  'Bellanova Raoul (D) (ATA)',
  'Bertola Nicolo (D) (UDI)',
  'Beukema Sam (D) (NAP)',
  'Bianchetti Matteo (D) (CRE)',
  'Biraghi Cristiano (D) (TOR)',
  'Bisseck Yann Aurel (D) (INT)',
  'Bonfanti Giovanni (D) (PIS)',
  'Bonifazi Kevin (D) (BOL)',
  'Bradaric Domagoji (D) (VER)',
  'Bremer Glaison (D) (JUV)',
  'Buongiorno Alessandro (D) (NAP)',
  'Cabal Juan (D) (JUV)',
  'Calabresi Arturo (D) (PIS)',
  'Cambiaso Andrea (D) (JUV)',
  'Candè Fali (D) (SAS)',
  'Canestrelli Simone (D) (PIS)',
  'Caracciolo Antonio (D) (PIS)',
  "Casale Nicolo' (D) (BOL)",
  'Ceccherini Federico (D) (CRE)',
  'Celik Zeki (D) (ROM)',
  'Cham Fallou (D) (VER)',
  'Circati Alessandro (D) (PAR)',
  'Coco Saul (D) (TOR)',
  'Comuzzo Pietro (D) (FIO)',
  'Cuadrado Juan (D) (PIS)',
  'Da Silva Jose Pedro (D) (CAG)',
  'Darmian Matteo (D) (INT)',
  'De Silvestri Lorenzo (D) (BOL)',
  'De Vrij Stefan (D) (INT)',
  'De Winter Koni (D) (MIL)',
  'Del Prato Enrico (D) (PAR)',
  'Dembelé Ali (D) (TOR)',
  'Denoon Daniel (D) (PIS)',
  'Di Lorenzo Giovanni (D) (NAP)',
  'Di Pardo Alessandro (D) (CAG)',
  'Dimarco Federico (D) (INT)',
  'Djimsiti Berat (D) (ATA)',
  "Dodo' Domilson (D) (FIO)",
  'Doig Josh (D) (SAS)',
  'Dossena Alberto (D) (COM)',
  'Dumfries Denzel (D) (INT)',
  'Ebosse Enzo (D) (VER)',
  'Ehizibue Kingsley (D) (UDI)',
  'Esteves Tomas (D) (PIS)',
  'Estupinan Pervis (D) (MIL)',
  'Floriani Mussolini Romano (D) (CRE)',
  'Folino Francesco (D) (CRE)',
  "Fortini Nicolo' (D) (FIO)",
  'Frese Martin (D) (VER)',
  'Gabbia Matteo (D) (MIL)',
  'Gabriel Tiago (D) (LEC)',
  'Gallo Antonino (D) (LEC)',
  'Gaspar Kiolanda (D) (LEC)',
  'Gatti Federico (D) (JUV)',
  'Ghilardi Daniele (D) (ROM)',
  'Gigot Samuel (D) (LAZ)',
  'Gila Mario (D) (LAZ)',
  'Goglichidze Saba (D) (UDI)',
  'Goldaniga Edoardo (D) (COM)',
  'Gosens Robin (D) (FIO)',
  'Guilbert Frederic (D) (LEC)',
  'Gutierrez Miguel (D) (NAP)',
  'Heggem Torbjor (D) (BOL)',
  'Hermoso Mario (D) (ROM)',
  'Hien Isak (D) (ATA)',
  'Holm Emil (D) (BOL)',
  'Hysaj Elseid (D) (LAZ)',
  'Idrissi Riyad (D) (CAG)',
  'Idzes Jay (D) (SAS)',
  'Ismajli Ardian (D) (TOR)',
  'Jean Gaby (D) (LEC)',
  'Jesus Juan (D) (NAP)',
  'Kalulu Pierre (D) (JUV)',
  'Kamara Hassane (D) (UDI)',
  'Kebasele Cristian (D) (UDI)',
  'Kelly Lloyd (D) (JUV)',
  'Kempf Marc Oliver (D) (COM)',
  'Kolasinac Sead (D) (ATA)',
  'Kouassi Christ-Owen (D) (LEC)',
  'Kristensen Thomas (D) (UDI)',
  'Lamptey Tariq (D) (FIO)',
  'Lazaro Valentino (D) (TOR)',
  'Lazzari Manuel (D) (LAZ)',
  'Lima Wesley (D) (ROM)',
  'Lovik Mathias (D) (PAR)',
  "Lucumi' Jhon (D) (BOL)",
  'Luperto Sebastiano (D) (CAG)',
  'Lusuardi Mateus (D) (PIS)',
  'Lykogiannis Charalampos (D) (BOL)',
  'Mancini Gianluca (D) (ROM)',
  'Marcandalli Alessandro (D) (GEN)',
  "Mari' Villar Pablo (D) (FIO)",
  'Marianucci Luca (D) (NAP)',
  'Mario Joao (D) (JUV)',
  'Maripan Guillermo (D) (TOR)',
  'Martin Aaron (D) (GEN)',
  'Marusic Adam (D) (LAZ)',
  'Masina Adam (D) (TOR)',
  'Mazzocchi Pasquale (D) (NAP)',
  'Mbambi Jeremy (D) (PIS)',
  'Mina Yerry (D) (CAG)',
  'Miranda Juan (D) (BOL)',
  'Modesto Rui (D) (UDI)',
  'Moreno Alberto (D) (COM)',
  'Muharemovic Tarik (D) (SAS)',
  'Mullen Senan (D) (TOR)',
  'Naveros Jacobo Ramon (D) (COM)',
  'Ndaba Corrie Richard (D) (LEC)',
  'Ndiaye Abdoulaye (D) (PAR)',
  'Ndicka Evan (D) (ROM)',
  'Nelsson Victor (D) (VER)',
  'Nkounkou Niels Patrick (D) (TOR)',
  'Norton-Cuffy Brooke (D) (GEN)',
  'Nunez Unai (D) (VER)',
  'Obert Adam (D) (CAG)',
  'Odenthal Cas (D) (SAS)',
  'Odogu David (D) (MIL)',
  'Olivera Mathias (D) (NAP)',
  'Ostigard Leo (D) (GEN)',
  'Otoa Sebastian (D) (GEN)',
  'Oyegoke Daniel (D) (VER)',
  'Palacios Tomas (D) (INT)',
  'Palestra Marco (D) (CAG)',
  'Palma Matteo (D) (UDI)',
  'Parisi Fabiano (D) (FIO)',
  'Patric Patricio Gabarron (D) (LAZ)',
  'Pavard Benjamin (D) (INT)',
  'Pavlovic Strahinja (D) (MIL)',
  'Paz Yefer son (D) (SAS)',
  'Pedersen Marcus (D) (TOR)',
  'Pellegrini Luca (D) (LAZ)',
  'Perez Matias (D) (LEC)',
  'Pezzella Giuseppe (D) (CRE)',
  'Pieragnolo Edoardo (D) (SAS)',
  'Pintus Nicola (D) (CAG)',
  'Pongracic Marin (D) (FIO)',
  'Posch Stefan (D) (COM)',
  'Provstgaard Oliver (D) (LAZ)',
  'Ranieri Luca (D) (FIO)',
  'Rensch Devyne (D) (ROM)',
  'Roberto Sergi (D) (COM)',
  'Rodriguez Juan (D) (CAG)',
  'Romagna Filippo (D) (SAS)',
  'Romagnoli Alessio (D) (LAZ)',
  'Rouhi Jonas Jakob (D) (JUV)',
  'Rrahmani Amir (D) (NAP)',
  'Rugani Daniele (D) (JUV)',
  'Sabelli Stefano (D) (GEN)',
  'Santos Silva Diego Carlos (D) (COM)',
  'Sazonov Saba (D) (TOR)',
  'Scalvini Giorgio (D) (ATA)',
  'Schuurs Perr (D) (TOR)',
  'Sernicola Leonardo (D) (CRE)',
  'Siebert Jamil (D) (LEC)',
  'Slotsager Tobias (D) (VER)',
  'Smolcic Ivan (D) (COM)',
  'Solet Oumar (D) (UDI)',
  'Spinazzola Leonardo (D) (NAP)',
  'Tavares Nuno (D) (LAZ)',
  'Terracciano Filippo (D) (CRE)',
  'Tomori Fikayo (D) (MIL)',
  'Toure Issak (D) (UDI)',
  'Troilo Mariano (D) (PAR)',
  'Tsimikas Konstantinos (D) (ROM)',
  'Ubani Marlon (D) (LEC)',
  'Valenti Lautaro (D) (PAR)',
  'Valentini Nicolas (D) (VER)',
  'Valeri Emanuele (D) (PAR)',
  'Valle Alex (D) (COM)',
  'Van Der Brempt Ignace (D) (COM)',
  'Vasquez Johan (D) (GEN)',
  'Veiga Danilo (D) (LEC)',
  'Viti Mattia (D) (FIO)',
  'Vitik Martin (D) (BOL)',
  'Vojvoda Mergim (D) (COM)',
  'Walukiewicz Sebastian (D) (SAS)',
  'Zalewski Nicola (D) (ATA)',
  'Zanoli Alessandro (D) (UDI)',
  'Zappa Gabriele (D) (CAG)',
  'Zappacosta Davide (D) (ATA)',
  'Zemura Jordan (D) (UDI)',
  'Ziolkowski Jan (D) (ROM)',
  'Zortea Nadir (D) (BOL)',

  //CENTROCAMPISTI
  'Adopo Michel (C) (CAG)',
  'Adzic Vasilije (C) (JUV)',
  'Aebischer Michel (C) (PIS)',
  'Akinsanmiro Ebenezer (C) (PIS)',
  'Akpa Akpro Jean Daniel (C) (VER)',
  'Al Murati Moatasem (C) (VER)',
  'Anguissa André Zambo (C) (NAP)',
  'Anjorin Tino (C) (TOR)',
  'Asllani Kristjan (C) (TOR)',
  'Atta Arthur (C) (UDI)',
  'Barella Nicolò (C) (INT)',
  'Basic Toma (C) (LAZ)',
  'Bayeye Brian Jephté (C) (TOR)',
  'Belahyane Reda (C) (LAZ)',
  'Berisha Medon (C) (LEC)',
  'Bernabè Adrian (C) (PAR)',
  'Bernede Antoine (C) (VER)',
  'Bianco Alessandro (C) (FIO)',
  'Boloca Daniel (C) (SAS)',
  'Bondo Warren (C) (CRE)',
  'Brescianini Marco (C) (ATA)',
  'Calhanoglu Hakan (C) (INT)',
  'Camara Drissa (C) (PAR)',
  'Caqueret Maxence (C) (COM)',
  'Casadei Cesare (C) (TOR)',
  'Cassa Federico (C) (ATA)',
  'Cataldi Danilo (C) (LAZ)',
  'Collocolo Michele (C) (CRE)',
  'Coulibaly Lassana (C) (LEC)',
  'Cristante Bryan (C) (ROM)',
  'Cyprien Wylan (C) (PAR)',
  'Da Cunha Lucas (C) (COM)',
  'De Bruyne Kevin (C) (NAP)',
  'De Roon Marten (C) (ATA)',
  'Deiola Alessandro (C) (CAG)',
  'Diouf Andy Alune (C) (INT)',
  'Ederson Dos Santos (C) (ATA)',
  'Ekkelenkamp Jurgen Peter (C) (UDI)',
  'El Aynaoui Neil (C) (ROM)',
  'Ellertsson Mikael Egill (C) (GEN)',
  'Elmas Elijf (C) (NAP)',
  'Estevez Nahuel (C) (PAR)',
  'Fabbian Giovanni (C) (BOL)',
  'Fagioli Nicolò (C) (FIO)',
  'Felici Mattia (C) (CAG)',
  'Ferguson Lewis (C) (BOL)',
  'Fofana Youssouf (C) (MIL)',
  'Folorunsho Michael (C) (CAG)',
  'Frattesi Davide (C) (INT)',
  'Frendrup Morten (C) (GEN)',
  'Freuler Remo (C) (BOL)',
  'Gilmour Billy (C) (NAP)',
  'Gineitis Gvidas (C) (TOR)',
  'Gorter Olaf (C) (LEC)',
  'Grassi Alberto (C) (CRE)',
  'Guendouzi Matteo (C) (LAZ)',
  'Harroui Abdou (C) (VER)',
  'Helgason Thorir J. (C) (LEC)',
  'Henrique Luis (C) (INT)',
  'Hernani Junior (C) (PAR)',
  'Hojholt Malthe (C) (PIS)',
  'Iannoni Edoardo (C) (SAS)',
  'Ilic Ivan (C) (TOR)',
  'Ilkhan Emirhan (C) (TOR)',
  'Infantino Gino (C) (FIO)',
  'Jashari Ardon (C) (MIL)',
  'Kaba Mohamed (C) (LEC)',
  'Karlstrom Jesper (C) (UDI)',
  'Keita Mandela (C) (PAR)',
  'Konè Ismael (C) (SAS)',
  'Kone Manu (C) (ROM)',
  'Koopmeiners Teun (C) (JUV)',
  'Kostic Filip (C) (JUV)',
  'Kovac Niko (C) (LEC)',
  'Leris Mehdi (C) (PIS)',
  'Lipani Luca (C) (SAS)',
  'Lobotka Stanislav (C) (NAP)',
  'Locatelli Manuel (C) (JUV)',
  'Loftus-Cheek Ruben (C) (MIL)',
  'Lordkipanidze Dachi (C) (CRE)',
  'Lovric Sandi (C) (UDI)',
  'Maleh Youssef (C) (LEC)',
  'Mandragora Rolando (C) (FIO)',
  'Marin Marius Mihai (C) (PIS)',
  'Masini Patrizio (C) (GEN)',
  'Matic Nemanja (C) (SAS)',
  'Mazzitelli Luca (C) (CAG)',
  'McKennie Weston (C) (JUV)',
  'McTominay Scott (C) (NAP)',
  'Miller Lennon Lee (C) (UDI)',
  'Miretti Fabio (C) (JUV)',
  'Mkhitaryan Henrikh (C) (INT)',
  'Modric Luka (C) (MIL)',
  'Moro Nikola (C) (BOL)',
  'Musah Yunus (C) (ATA)',
  'Ndour Cher (C) (FIO)',
  'Niasse Cheikh (C) (VER)',
  'Nicolussi Caviglia Hans (C) (FIO)',
  'Onana Jean (C) (GEN)',
  'Ordonez Christian Nahuel (C) (PAR)',
  'Pasalic Mario (C) (ATA)',
  'Payero Martin (C) (CRE)',
  'Pellegrini Lorenzo (C) (ROM)',
  'Perrone Maximo (C) (COM)',
  'Piccinini Gabriele (C) (PIS)',
  'Pierret Balthazar (C) (LEC)',
  'Piotrowski Jakub (C) (UDI)',
  'Pisilli Niccolò (C) (ROM)',
  'Pobega Tommaso (C) (BOL)',
  'Prati Matteo (C) (CAG)',
  'Rabiot Adrien (C) (MIL)',
  'Ramadani Ylber (C) (LEC)',
  'Ricci Samuele (C) (MIL)',
  'Richardson Amir (C) (FIO)',
  'Rog Marko (C) (CAG)',
  'Rovella Nicolò (C) (LAZ)',
  'Saelemaekers Alexis (C) (MIL)',
  'Sala Herrero Ólex (C) (LEC)',
  'Samardzic Lazar (C) (ATA)',
  'Santiago Perez Jesus (C) (VER)',
  'Serdar Suat (C) (VER)',
  'Sohm Simon (C) (FIO)',
  'Sorensen Jensen Olivier (C) (PAR)',
  'Stanciu Nicolae (C) (GEN)',
  'Sucic Petar (C) (INT)',
  'Sulemana Ibrahim (C) (BOL)',
  'Suslov Tomas (C) (VER)',
  'Tameze Adrien (C) (TOR)',
  'Thorsby Morten (C) (GEN)',
  'Thorstvedt Kristian (C) (SAS)',
  'Thuram Khephren (C) (JUV)',
  'Tourè Idrissa (C) (PIS)',
  'Valoti Mattia (C) (CRE)',
  'Vecino Matias (C) (LAZ)',
  'Volpato Cristian (C) (SAS)',
  'Vrankx Aster (C) (SAS)',
  'Vural İsak (C) (PIS)',
  'Zarraga Oier (C) (UDI)',
  'Zerbin Alessio (C) (CRE)',
  'Zielinski Piotr (C) (INT)',
  'Bailey Leon Patrick (C) (ROM)',
  'Baldanzi Tommaso (C) (ROM)',
  'Baturina Martin (C) (COM)',
  'Begic Tjas (C) (PAR)',
  'Bernardeschi Federico (C) (BOL)',
  'Carboni Valentin (C) (GEN)',
  'Cornet Maxwel (C) (GEN)',
  'Cuenca Hugo (C) (GEN)',
  'De Ketelaere Charles (C) (ATA)',
  'De Souza Lorran (C) (PIS)',
  'Dele-Bashiru Fisayo (C) (LAZ)',
  'Fadera Alieu (C) (SAS)',
  'Fazzini Jacopo (C) (FIO)',
  'Franco Vazquez (C) (CRE)',
  'Gaetano Gianluca (C) (CAG)',
  'Gronbaek Albert (C) (GEN)',
  'Gudmundsson Albert (C) (FIO)',
  'Johnsen Dennis (C) (CRE)',
  'Kastanos Grigoris (C) (VER)',
  'Maldini Daniel (C) (ATA)',
  'Malinovskyi Ruslan (C) (GEN)',
  'Marchwinski Filip (C) (LEC)',
  'Messias Junior (C) (GEN)',
  'Neres David (C) (NAP)',
  'Odgaard Jens (C) (BOL)',
  'Ondrejka Jacob (C) (PAR)',
  'Oristanio Gaetano (C) (PAR)',
  'Orsolini Riccardo (C) (BOL)',
  'Paz Nico (C) (COM)',
  'Perciun Sergiu (C) (TOR)',
  'Politano Matteo (C) (NAP)',
  'Pulisic Christian (C) (MIL)',
  'Rafia Hamza (C) (LEC)',
  'Sabiri Abdelhamid (C) (FIO)',
  'Sottil Riccardo (C) (LEC)',
  'Stengs Calvin (C) (PIS)',
  'Tramoni Matteo (C) (PIS)',
  'Vandeputte Jari (C) (CRE)',
  'Vergara Antonio (C) (NAP)',
  'Vlasic Nikola (C) (TOR)',
  'Zaccagni Mattia (C) (LAZ)',
  'Zaniolo Nicolò (C) (UDI)',
  'Zhegrova Edon (C) (JUV)',

  //ATTACCANTI
  'Aboukhlal Zakaria (A) (TOR)',
  'Adams Chè (A) (TOR)',
  'Ajayi Junior (A) (VER)',
  'Alessandro Vinciguerra (A) (CAG)',
  'Almqvist Pontus (A) (PAR)',
  'Ambrosino Giuseppe (A) (NAP)',
  'Banda Lameck (A) (LEC)',
  'Bayo Vakoun (A) (UDI)',
  'Belotti Andrea (A) (CAG)',
  'Benedyczak Adrian (A) (PAR)',
  'Berardi Domenico (A) (SAS)',
  'Bonazzoli Federico (A) (CRE)',
  'Bonny Ange-Yoan (A) (INT)',
  'Borrelli Gennaro (A) (CAG)',
  'Buksa Adam (A) (UDI)',
  'Burnete Rares (A) (LEC)',
  'Camarda Francesco (A) (LEC)',
  'Cambiaghi Nicolo (A) (BOL)',
  'Cancellieri Matteo (A) (LAZ)',
  'Castellanos Taty (A) (LAZ)',
  'Castro Santiago (A) (BOL)',
  'Cheddira Walid (A) (SAS)',
  'Colombo Lorenzo (A) (GEN)',
  'Conceicao Francisco (A) (JUV)',
  'Cutrone Patrick (A) (PAR)',
  'Dallinga Thijs (A) (BOL)',
  'David Jonathan Christian (A) (JUV)',
  'Davis Keinan (A) (UDI)',
  'De Luca Manuel (A) (CRE)',
  'Dia Boulaye (A) (LAZ)',
  'Diao Assane (A) (COM)',
  'Djuric Milan (A) (PAR)',
  'Dominguez Benja (A) (BOL)',
  'Douvikas Anastasios (A) (COM)',
  'Dovbyk Artem (A) (ROM)',
  'Dybala Paulo (A) (ROM)',
  'Dzeko Edin (A) (FIO)',
  'Ekhator Osayuki Jeff (A) (GEN)',
  'Ekuban Caleb (A) (GEN)',
  'El Shaarawy Stephan (A) (ROM)',
  'Esposito Francesco Pio (A) (INT)',
  'Esposito Sebastiano (A) (CAG)',
  'Ferguson Evan (A) (ROM)',
  'Fini Seydou (A) (GEN)',
  'Frigan Matija (A) (PAR)',
  'Gimenez Santiago (A) (MIL)',
  'Gueye Idrissa (A) (UDI)',
  'Hojlund Rasmus (A) (NAP)',
  'Ibrahimovic Arijon (A) (LAZ)',
  'Immobile Ciro (A) (BOL)',
  'Isaksen Gustav (A) (LAZ)',
  'Kean Moise (A) (FIO)',
  'Kilicsoy Semih (A) (CAG)',
  'Kouame Christian (A) (FIO)',
  'Krstovic Nikola (A) (ATA)',
  'Kuhn Nicolas-Gerrit (A) (COM)',
  'Lang Noa Noell (A) (NAP)',
  'Lauriente Armand (A) (SAS)',
  'Leao Rafael (A) (MIL)',
  'Lookman Ademola (A) (ATA)',
  'Lucca Lorenzo (A) (NAP)',
  'Lukaku Romelu (A) (NAP)',
  'Luvumbo Zito (A) (CAG)',
  'Martinez Lautaro (A) (INT)',
  'Meister Henrik (A) (PIS)',
  'Milik Arkadiusz (A) (JUV)',
  'Morata Alvaro (A) (COM)',
  'Morente Tete (A) (LEC)',
  'Moreo Stefano (A) (PIS)',
  'Moro Luca (A) (SAS)',
  'Mosquera Daniel (A) (VER)',
  "N'dri Konan (A) (LEC)",
  'Ngonge Cyril (A) (TOR)',
  'Njie Alieu (A) (TOR)',
  'Nkunku Christopher (A) (MIL)',
  'Noslin Tijjani (A) (LAZ)',
  "Nzola M'bala (A) (PIS)",
  'Okereke David (A) (CRE)',
  'Openda Lois (A) (JUV)',
  'Orban Gift (A) (VER)',
  'Osei Addai Jayden (A) (COM)',
  'Pavoletti Leonardo (A) (CAG)',
  'Pedro Eleizier R. Ledesma (A) (LAZ)',
  'Pellegrino Mateo (A) (PAR)',
  'Pemi Moumbagna Faris (A) (CRE)',
  'Piccoli Roberto (A) (FIO)',
  'Pierini Nicholas (A) (SAS)',
  'Pierotti Santiago Daniel (A) (LEC)',
  'Pinamonti Andrea (A) (SAS)',
  'Rodriguez Caraballo Jesus (A) (COM)',
  'Rowe Jonathan David Henry (A) (BOL)',
  'Sanabria Antonio (A) (CRE)',
  'Santana Do Nascimento Giovane (A) (VER)',
  'Sarr Amin (A) (VER)',
  'Savva Zanos (A) (TOR)',
  'Scamacca Gianluca (A) (ATA)',
  'Simeone Giovanni (A) (TOR)',
  'Skjellerup Laurs (A) (SAS)',
  "Soule' Matias (A) (ROM)",
  'Stulic Nikola (A) (LEC)',
  'Sulemana Kamaldeen (A) (ATA)',
  'Thuram Marcus (A) (INT)',
  'Traore Chaka (A) (MIL)',
  'Vardy Jamie Richard (A) (CRE)',
  'Vitinha Vitor Manuel (A) (GEN)',
  'Vlahovic Dusan (A) (JUV)',
  'Yildiz Kenan (A) (JUV)',
  'Zapata Duvan (A) (TOR)',
];

export default PLAYERS;
